package com.example.android_app_new;

import android.content.Context;
import android.os.Environment;
import android.util.Log;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;

public class ReportExporter {
    private static final String TAG = "ReportExporter";
    private Context context;

    public ReportExporter(Context context) {
        this.context = context;
    }

    /**
     * Export AQI data to CSV file
     */
    public File exportToCSV(String city, ArrayList<AqiTrendData> trendData,
                           int currentAqi, double pm25, double pm10, double no2, double o3) {
        try {
            File reportsDir = getReportsDirectory();
            if (!reportsDir.exists()) {
                reportsDir.mkdirs();
            }

            String fileName = "AQI_Report_" + city + "_" + getCurrentTimestamp() + ".csv";
            File csvFile = new File(reportsDir, fileName);

            FileWriter writer = new FileWriter(csvFile);

            // Write header
            writer.append("Air Quality Index Report\n");
            writer.append("City,").append(city).append("\n");
            writer.append("Report Date,").append(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(new Date())).append("\n");
            writer.append("Current AQI,").append(String.valueOf(currentAqi)).append("\n");
            writer.append("\n");

            // Write current pollutant levels
            writer.append("Current Pollutant Levels\n");
            writer.append("Pollutant,Value,Unit,Status\n");
            writer.append("PM2.5,").append(String.format(Locale.getDefault(), "%.2f", pm25)).append(",µg/m³,").append(getPollutantStatus(pm25, "pm25")).append("\n");
            writer.append("PM10,").append(String.format(Locale.getDefault(), "%.2f", pm10)).append(",µg/m³,").append(getPollutantStatus(pm10, "pm10")).append("\n");
            writer.append("NO2,").append(String.format(Locale.getDefault(), "%.2f", no2)).append(",ppb,").append(getPollutantStatus(no2, "no2")).append("\n");
            writer.append("O3,").append(String.format(Locale.getDefault(), "%.2f", o3)).append(",ppb,").append(getPollutantStatus(o3, "o3")).append("\n");
            writer.append("\n");

            // Write 7-day trend
            writer.append("7-Day Trend\n");
            writer.append("Date,AQI,Status,PM2.5,PM10,NO2,O3\n");

            for (AqiTrendData data : trendData) {
                writer.append(data.getDate()).append(",");
                writer.append(String.format(Locale.getDefault(), "%.1f", data.getAqi())).append(",");
                writer.append(data.getStatus()).append(",");
                writer.append(String.format(Locale.getDefault(), "%.2f", data.getPm25())).append(",");
                writer.append(String.format(Locale.getDefault(), "%.2f", data.getPm10())).append(",");
                writer.append(String.format(Locale.getDefault(), "%.2f", data.getNo2())).append(",");
                writer.append(String.format(Locale.getDefault(), "%.2f", data.getO3())).append("\n");
            }

            writer.append("\n");
            writer.append("Notes,Report generated by Air Quality Predictor App\n");

            writer.flush();
            writer.close();

            Log.d(TAG, "CSV exported successfully: " + csvFile.getAbsolutePath());
            return csvFile;

        } catch (IOException e) {
            Log.e(TAG, "Error exporting CSV: " + e.getMessage());
            return null;
        }
    }

    /**
     * Export AQI data to text report
     */
    public File exportToTextReport(String city, ArrayList<AqiTrendData> trendData,
                                   int currentAqi, double pm25, double pm10, double no2, double o3,
                                   HealthRecommendationEngine.HealthRecommendation healthRec) {
        try {
            File reportsDir = getReportsDirectory();
            if (!reportsDir.exists()) {
                reportsDir.mkdirs();
            }

            String fileName = "AQI_Report_" + city + "_" + getCurrentTimestamp() + ".txt";
            File reportFile = new File(reportsDir, fileName);

            FileWriter writer = new FileWriter(reportFile);

            // Header
            writer.write("╔════════════════════════════════════════════════════════════╗\n");
            writer.write("║          AIR QUALITY DETAILED REPORT                       ║\n");
            writer.write("╚════════════════════════════════════════════════════════════╝\n\n");

            // Location and Date
            writer.write("REPORT DETAILS\n");
            writer.write("═════════════════════════════════════════\n");
            writer.write("City: " + city + "\n");
            writer.write("Report Date: " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(new Date()) + "\n");
            writer.write("Current AQI: " + currentAqi + "\n\n");

            // Current Pollutant Levels
            writer.write("CURRENT POLLUTANT LEVELS\n");
            writer.write("═════════════════════════════════════════\n");
            writer.write(String.format(Locale.getDefault(), "PM2.5:  %.2f µg/m³  [%s]\n", pm25, getPollutantStatus(pm25, "pm25")));
            writer.write(String.format(Locale.getDefault(), "PM10:   %.2f µg/m³  [%s]\n", pm10, getPollutantStatus(pm10, "pm10")));
            writer.write(String.format(Locale.getDefault(), "NO2:    %.2f ppb    [%s]\n", no2, getPollutantStatus(no2, "no2")));
            writer.write(String.format(Locale.getDefault(), "O3:     %.2f ppb    [%s]\n\n", o3, getPollutantStatus(o3, "o3")));

            // 7-Day Trend
            writer.write("7-DAY TREND ANALYSIS\n");
            writer.write("═════════════════════════════════════════\n");
            for (AqiTrendData data : trendData) {
                writer.write(String.format(Locale.getDefault(), "%-10s AQI: %5.1f  Status: %-15s  " +
                                          "PM2.5: %6.2f  PM10: %6.2f  NO2: %6.2f  O3: %6.2f\n",
                        data.getDate(), data.getAqi(), data.getStatus(),
                        data.getPm25(), data.getPm10(), data.getNo2(), data.getO3()));
            }
            writer.write("\n");

            // Health Recommendations
            if (healthRec != null) {
                writer.write("HEALTH RECOMMENDATIONS\n");
                writer.write("═════════════════════════════════════════\n");
                writer.write(healthRec.getFullRecommendation());
                writer.write("\n");
            }

            // Footer
            writer.write("═════════════════════════════════════════\n");
            writer.write("Generated by: Air Quality Predictor App\n");
            writer.write("Report Type: Comprehensive AQI Analysis\n");
            writer.write("═════════════════════════════════════════\n");

            writer.flush();
            writer.close();

            Log.d(TAG, "Text report exported successfully: " + reportFile.getAbsolutePath());
            return reportFile;

        } catch (IOException e) {
            Log.e(TAG, "Error exporting text report: " + e.getMessage());
            return null;
        }
    }

    /**
     * Export AQI data to JSON
     */
    public File exportToJSON(String city, ArrayList<AqiTrendData> trendData,
                            int currentAqi, double pm25, double pm10, double no2, double o3) {
        try {
            File reportsDir = getReportsDirectory();
            if (!reportsDir.exists()) {
                reportsDir.mkdirs();
            }

            String fileName = "AQI_Report_" + city + "_" + getCurrentTimestamp() + ".json";
            File jsonFile = new File(reportsDir, fileName);

            FileWriter writer = new FileWriter(jsonFile);

            // Write JSON
            writer.write("{\n");
            writer.write("  \"city\": \"" + city + "\",\n");
            writer.write("  \"reportDate\": \"" + new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(new Date()) + "\",\n");
            writer.write("  \"currentAQI\": " + currentAqi + ",\n");
            writer.write("  \"pollutants\": {\n");
            writer.write("    \"PM2.5\": " + pm25 + ",\n");
            writer.write("    \"PM10\": " + pm10 + ",\n");
            writer.write("    \"NO2\": " + no2 + ",\n");
            writer.write("    \"O3\": " + o3 + "\n");
            writer.write("  },\n");
            writer.write("  \"trendData\": [\n");

            for (int i = 0; i < trendData.size(); i++) {
                AqiTrendData data = trendData.get(i);
                writer.write("    {\n");
                writer.write("      \"date\": \"" + data.getDate() + "\",\n");
                writer.write("      \"aqi\": " + data.getAqi() + ",\n");
                writer.write("      \"status\": \"" + data.getStatus() + "\",\n");
                writer.write("      \"pm25\": " + data.getPm25() + ",\n");
                writer.write("      \"pm10\": " + data.getPm10() + ",\n");
                writer.write("      \"no2\": " + data.getNo2() + ",\n");
                writer.write("      \"o3\": " + data.getO3() + "\n");
                writer.write("    }" + (i < trendData.size() - 1 ? "," : "") + "\n");
            }

            writer.write("  ]\n");
            writer.write("}\n");

            writer.flush();
            writer.close();

            Log.d(TAG, "JSON exported successfully: " + jsonFile.getAbsolutePath());
            return jsonFile;

        } catch (IOException e) {
            Log.e(TAG, "Error exporting JSON: " + e.getMessage());
            return null;
        }
    }

    /**
     * Get reports directory
     */
    private File getReportsDirectory() {
        File reportsDir = new File(context.getExternalFilesDir(null), "AQI_Reports");
        return reportsDir;
    }

    /**
     * Get current timestamp for filename
     */
    private String getCurrentTimestamp() {
        return new SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(new Date());
    }

    /**
     * Get pollutant status based on value
     */
    private String getPollutantStatus(double value, String pollutant) {
        switch (pollutant) {
            case "pm25":
                if (value > 35.4) return "CRITICAL";
                if (value > 11.8) return "ELEVATED";
                return "GOOD";
            case "pm10":
                if (value > 154) return "CRITICAL";
                if (value > 54) return "ELEVATED";
                return "GOOD";
            case "no2":
                if (value > 200) return "CRITICAL";
                if (value > 100) return "ELEVATED";
                return "GOOD";
            case "o3":
                if (value > 120) return "CRITICAL";
                if (value > 80) return "ELEVATED";
                return "GOOD";
            default:
                return "UNKNOWN";
        }
    }
}

